[package]
name = "rosalia64"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rosalia_core"
path = "src/lib.rs"

[[bin]]
name = "rosalia_petal"
path = "src/petal/main.rs"

[dependencies]
exe = "0.5.5"